# Generated by Django 2.2 on 2020-08-03 19:17

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20200803_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app_one.Post')),
                ('video_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_poster', to='app_one.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
