# Generated by Django 2.2 on 2020-08-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20200809_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='app_one.User'),
            preserve_default=False,
        ),
    ]
