# Generated by Django 2.2 on 2020-08-03 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20200803_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video_item',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app_one.Post'),
        ),
        migrations.AlterField(
            model_name='video_item',
            name='video_poster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_poster', to='app_one.User'),
        ),
    ]
