# Generated by Django 2.2 on 2020-08-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20200809_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
