# Generated by Django 2.2 on 2020-08-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0006_auto_20200809_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post_images'),
        ),
    ]
